import Head from "next/head"
import Link from "next/link"
import { useCurrentUser } from "../src/hooks/auth/useCurrentUser"
import styles from "../styles/Home.module.css"

export default function Home() {
  const { user: currentUser } = useCurrentUser()

  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS JWT Auth</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          DevIT Blog Test Task
        </h1>

        <p className={styles.description}>
          {currentUser
            ? `Hello ${currentUser.name}`
            : "You are not logged in !"}
        </p>

        <div className={styles.grid}>
          <Link href="/login" className={styles.card}>
            <h2>Login Page &rarr;</h2>
            <p>This is a private route for unauthenticated user!</p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
